# config/packages/vich_uploader.yaml
vich_uploader:
    db_driver: orm
    metadata:
        type: attribute

    mappings:
        ressource_file:
            uri_prefix: /uploads/ressources
            upload_destination: '%kernel.project_dir%/public/uploads/ressources'
            namer: Vich\UploaderBundle\Naming\OrignameNamer
            directory_namer: ~
            delete_on_update: true
            delete_on_remove: true
            inject_on_load: false